### ISSUE TITLE
yaml subtopic filtering

### ISSUE THREAD

**Issue by Jibec** [mquinson/po4a#187]
hello,

I have this file:
```yaml
# Name will be mostly visible in the URL. Treat it as an indentifier.
# Tip: If you want to use the local preview scripts that come with this repository, please change this value in the site.yml file as well. (under site/start_page)
name: project

# Title will be visible on the page.
title: Fedora Project

# If you don't plan to have multiple versions of the docs (for example, to document multiple versions of some software), you can ignore this field. Otherwise, change "master" to a specific version.
version: master

# We encourage you to name the index page as "index.adoc". If you absolutely have to use a different name, please reflect it here. You can ignore this field otherwise.
start_page: ROOT:index

# This lists all the menu definitions of your component.
nav:
- modules/ROOT/nav.adoc
```

I run:
```bash
po4a-gettextize \
    --format "yaml" \
    --debug \
    --option "keys=title" \
    --master "my_file.yml" \
    --master-charset "UTF-8" \
    --localized-charset "UTF-8" \
    --po "out.pot"
```

I get:
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2019-11-06 23:13+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#. type: Array Element
#: >nav
#, no-wrap
msgid "modules/ROOT/nav.adoc"
msgstr ""

#. type: Hash Value - Key: title
#, no-wrap
msgid "Fedora Project"
msgstr ""
```

Expected: only have the "Fedora Project". As far as I understand, the sequence in Yaml format isn't a key.

kind ping to @bexelbie who wrote the parser
